"""add taiga_user_id and taiga_webhook_event

Revision ID: 066fb7f8c30b
Revises: 022db256ae49
Create Date: 2026-09-17 01:22:17.677498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '066fb7f8c30b'
down_revision: Union[str, Sequence[str], None] = '022db256ae49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taiga_webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taiga_webhook_event_fingerprint'), 'taiga_webhook_event', ['fingerprint'], unique=True)
    op.add_column('taiga_session', sa.Column('taiga_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_taiga_session_taiga_user_id'), 'taiga_session', ['taiga_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taiga_session_taiga_user_id'), table_name='taiga_session')
    op.drop_column('taiga_session', 'taiga_user_id')
    op.drop_index(op.f('ix_taiga_webhook_event_fingerprint'), table_name='taiga_webhook_event')
    op.drop_table('taiga_webhook_event')
    # ### end Alembic commands ###
