"""create taiga_session table

Revision ID: 3eca24ca14f5
Revises: 
Create Date: 2026-09-16 21:29:27.514747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3eca24ca14f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taiga_session',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taiga_session')
    # ### end Alembic commands ###
