"""add telegram_message_log table

Revision ID: 45a88ff42bfd
Revises: 5850a21b6d0c
Create Date: 2026-09-17 19:20:31.215381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a88ff42bfd'
down_revision: Union[str, Sequence[str], None] = '5850a21b6d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_message_log_chat_id'), 'telegram_message_log', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_message_log_chat_id'), table_name='telegram_message_log')
    op.drop_table('telegram_message_log')
    # ### end Alembic commands ###
