"""add taiga_full_name to taiga_session

Revision ID: 5850a21b6d0c
Revises: dd7fe4dfa0e1
Create Date: 2026-09-17 15:05:54.353372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5850a21b6d0c'
down_revision: Union[str, Sequence[str], None] = 'dd7fe4dfa0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taiga_session', sa.Column('taiga_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taiga_session', 'taiga_full_name')
    # ### end Alembic commands ###
