"""add taiga assignment notification table

Revision ID: 76d0f268083f
Revises: 066fb7f8c30b
Create Date: 2026-09-17 02:03:07.519877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76d0f268083f'
down_revision: Union[str, Sequence[str], None] = '066fb7f8c30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taiga_assignment_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taiga_object_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taiga_object_id', sa.Integer(), nullable=False),
    sa.Column('taiga_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taiga_object_type', 'taiga_object_id', 'taiga_user_id', name='uq_taiga_assignment_notification_object_user')
    )
    op.create_index(op.f('ix_taiga_assignment_notification_taiga_user_id'), 'taiga_assignment_notification', ['taiga_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taiga_assignment_notification_taiga_user_id'), table_name='taiga_assignment_notification')
    op.drop_table('taiga_assignment_notification')
    # ### end Alembic commands ###
