"""add taiga status notification table

Revision ID: 923643ed59bd
Revises: 45a88ff42bfd
Create Date: 2026-09-18 01:23:31.347622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '923643ed59bd'
down_revision: Union[str, Sequence[str], None] = '45a88ff42bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taiga_status_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taiga_object_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taiga_object_id', sa.Integer(), nullable=False),
    sa.Column('taiga_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taiga_object_type', 'taiga_object_id', 'taiga_user_id', name='uq_taiga_status_notification_object_user')
    )
    op.create_index(op.f('ix_taiga_status_notification_taiga_user_id'), 'taiga_status_notification', ['taiga_user_id'], unique=False)
    op.create_table('telegram_menu_anchor',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_menu_anchor')
    op.drop_index(op.f('ix_taiga_status_notification_taiga_user_id'), table_name='taiga_status_notification')
    op.drop_table('taiga_status_notification')
    # ### end Alembic commands ###
