"""add taiga_due_date_reminder table

Revision ID: dd7fe4dfa0e1
Revises: 76d0f268083f
Create Date: 2026-09-17 13:36:30.872341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd7fe4dfa0e1'
down_revision: Union[str, Sequence[str], None] = '76d0f268083f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taiga_due_date_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taiga_object_id', sa.Integer(), nullable=False),
    sa.Column('taiga_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('window', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taiga_object_id', 'taiga_user_id', 'window', name='uq_taiga_due_date_reminder_object_user_window')
    )
    op.create_index(op.f('ix_taiga_due_date_reminder_taiga_user_id'), 'taiga_due_date_reminder', ['taiga_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taiga_due_date_reminder_taiga_user_id'), table_name='taiga_due_date_reminder')
    op.drop_table('taiga_due_date_reminder')
    # ### end Alembic commands ###
